version: "3.8"

services:
  # Database persistence
  postgresdb:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  # Celery broker
  redis:
    image: redis:6.0.9-alpine3.12
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
  # Elasticsearch, for document query/search
  elastic:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single.node
    ports:
      - "9200:9200"
      - "9300:9300"
  # Django web application
  web:
    build: .
    environment:
      - POSTGRES_HOST=postgresdb
      - REDIS_HOST=redis
      - ELASTICSEARCH_HOST=elastic
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgresdb
      - redis
      - elastic
    depends_on:
      - postgresdb
      - redis
      - elastic
  # Celery worker (periodic tasks beat)
  celery:
    build: .
    environment:
      - POSTGRES_HOST=postgresdb
      - REDIS_HOST=redis
      - ELASTICSEARCH_HOST=elastic
    command:
      celery -A semscrape worker --beat --loglevel=INFO
    links:
      - redis
      - postgresdb
      - elastic
    depends_on:
      - web
      - postgresdb
      - redis
      - elastic
