version: "3.8"

services:
  # Database persistence
  postgresdb:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  # Celery broker
  redis:
    image: redis:6.0.9-alpine3.12
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - ./redis_data:/var/lib/redis
      - ./redis_conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  # Elasticsearch, for document query/search
  elastic:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - ES_HEAP_SIZE:512m
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 512m
    mem_reservation: 512m
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  # Django web application
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: semscrape
    environment:
      - DJANGO_DEBUG=true
      - POSTGRES_HOST=postgresdb
      - REDIS_HOST=redis
      - ELASTIC_HOST=elastic
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver --insecure 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - postgresdb
      - redis
      - elastic
    depends_on:
      - postgresdb
      - redis
      - elastic
  # Celery worker (periodic tasks beat)
  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: semscrape
    environment:
      - DJANGO_DEBUG=false
      - POSTGRES_HOST=postgresdb
      - REDIS_HOST=redis
      - ELASTIC_HOST=elastic
    command:
      # each child gets 3GB RAM or dies
      celery -A semscrape worker --beat --concurrency=4 --max-memory-per-child 3000000 --loglevel=INFO
    volumes:
      - .:/code
    links:
      - redis
      - postgresdb
      - elastic
    depends_on:
      - web
      - postgresdb
      - redis
      - elastic
