# Generated by Django 3.1.3 on 2020-11-05 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0002_cnn_rss_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSSEntry",
            fields=[
                ("link", models.URLField(primary_key=True, serialize=False)),
                ("title", models.TextField(db_index=True)),
                ("description", models.TextField(blank=True)),
                ("pub_date", models.DateTimeField(null=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.rssfeed",
                    ),
                ),
            ],
        ),
    ]
