# Generated by Django 3.1.3 on 2020-11-06 19:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0004_rssentry_dl_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=2048, null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), default=list, size=None)),
                ('author', models.CharField(default=None, max_length=2048, null=True)),
                ('body', models.TextField(default=None, null=True)),
                ('rss_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crawler.rssentry')),
            ],
        ),
    ]
