# Generated by Django 3.1.3 on 2020-11-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="sentiment",
            field=models.JSONField(default=dict),
        )
    ]
